apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.0.0
    helm:
      values: |
        persistence:
          enabled: false
        admin:
          existingSecret: grafana-admin
          userKey: admin-user
          passwordKey: admin-password
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
              - name: Loki
                type: loki
                url: http://loki.monitoring.svc.cluster.local:3100
                jsonData:
                  httpHeaderName1: X-Scope-OrgID
                secureJsonData:
                  httpHeaderValue1: fake

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
