apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.154.0
    helm:
      values: |
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-contrib
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
        extraVolumes:
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdocker
            hostPath:
              path: /var/lib/docker/containers
        extraVolumeMounts:
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlibdocker
            mountPath: /var/lib/docker/containers
            readOnly: true
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            filelog:
              include:
                - /var/log/pods/*/*/*.log
              include_file_path: true
              start_at: end
          exporters:
            otlphttp/loki:
              endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
            prometheus:
              endpoint: 0.0.0.0:8889
          processors:
            batch:
              send_batch_size: 100
              send_batch_max_size: 200
              timeout: 5s
          service:
            telemetry:
              logs:
                level: debug
            pipelines:
              logs:
                receivers: [filelog]
                processors: [batch]
                exporters: [otlphttp/loki]
              metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
