apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - argocd.localhost
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-tls
  namespace: traefik
spec:
  secretName: traefik-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - dashboard.localhost
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - vault.localhost
