apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tamagotchi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: tamagotchi
          port: {{ .Values.service.port }}
  tls:
    secretName: tamagotchi-tls
